### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by EntityCat** [ItzFreshyyy/Musicat#9]
When I use command,the plugin will return a usage of it.So I can't play music
version:1.11.2

**Comment by ItzFreshyyy** [comment]
What are exactly you entering?

**Comment by ItzFreshyyy** [comment]
For me everything works on 1.11.2. :/

**Comment by ItzFreshyyy** [comment]
Also Musicat doesn't programmed to print usage of it. Did you modified code of it?

**Comment by ItzFreshyyy** [comment]
Well seems like it's not my fault because everything works on 1.11.2, I will close this issue and reopen after if it is really a bug.
